### ISSUE TITLE
InstantX Flux Union ControlNet Loader node not found

### ISSUE THREAD

**Issue by local306** [EeroHeikkinen/ComfyUI-eesahesNodes#5]
This is a follow up to my [Reddit post](https://www.reddit.com/r/StableDiffusion/comments/1euz2a9/comment/lisfgg9/?context=3) where I am not having any luck getting this package to work in ComfyUI. Just to reiterate to have the information on here, this is what I mentioned:

> Hmm, I keep getting:
> 
```
> Warning: Missing Node Types
> 
> When loading the graph, the following node types were not found:
> 
> InstantX Flux Union ControlNet Loader
> 
> No selected item
> 
> Nodes that have failed to load will show as red on the graph.
```
> 
> Updating the node via the manager doesn't resolve anything. My ComfyUI is up to date as well as my Union Flux hash is the same as the currently available.

I did as you suggested and looked at my node manager > import failed. Nothing is listed here unfortunately.

Looking at the console log, I saw this:

```
  File "M:\Users\Shane\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\Users\Shane\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-eesahesNodes\__init__.py", line 8, in <module>
    from .nodes import InstantXFluxUnionControlNetLoader
  File "M:\Users\Shane\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-eesahesNodes\nodes.py", line 6, in <module>
    from .controlnet.controlnet_instantx import InstantXControlNetFlux
  File "M:\Users\Shane\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-eesahesNodes\controlnet\controlnet_instantx.py", line 16, in <module>
    from diffusers.models.transformers.transformer_flux import FluxSingleTransformerBlock, FluxTransformerBlock
ModuleNotFoundError: No module named 'diffusers.models.transformers.transformer_flux'

Cannot import M:\Users\Shane\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-eesahesNodes module for custom nodes: No module named 'diffusers.models.transformers.transformer_flux'
```

**Comment by EeroHeikkinen** [comment]
Hi, could you try running this command and see if that helps:

`M:\Users\Shane\Documents\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -U diffusers
`

**Comment by jepjoo** [comment]
I had the same issue and that (updating diffusers) worked, thanks.

**Comment by local306** [comment]
> Hi, could you try running this command and see if that helps:
> 
> `M:\Users\Shane\Documents\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -U diffusers `

That did the trick. Thanks @EeroHeikkinen

**Comment by Th3Disasterpiece** [comment]
> Hi, could you try running this command and see if that helps:
> 
> `M:\Users\Shane\Documents\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -U diffusers `

Hi, How could one go about this on a macOS?
