### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by iovart** [EeroHeikkinen/ComfyUI-eesahesNodes#9]
Hi! The node is not displaying. What's the problem?
![1](https://github.com/user-attachments/assets/6c6a496e-5dd6-4e6d-be0c-08ecece9d7f1)

**Comment by jepjoo** [comment]
https://github.com/EeroHeikkinen/ComfyUI-eesahesNodes/issues/5

**Comment by iovart** [comment]
@jepjoo Thanks!
